version: '3'

services:

  movasat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/movasat
      - movasat_static_volume:/movasat/static
      - movasat_files_volume:/movasat/files
    restart: always
    ports:
      - "8004:8004"
    networks:
      - movasat_network
      - nginx_network
    depends_on:
      - movasat_postgresql
  movasat_postgresql:
    image: postgres:12
    container_name: movasat_postgresql
    volumes:
      - movasat_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5434:5432"
    networks:
      - movasat_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: saelozahra14@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Yaheydar110
    ports:
      - "5050:80"
    networks:
      - movasat_network
      - nginx_network

#  mongo:
#    image: mongo
#    container_name: mongo
#    restart: always
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=example
#      - MONGO_INITDB_DATABASE=admin
#      - MONGO_INITDB_USERNAME=root
#      - MONGO_INITDB_PASSWORD=example
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data/db
#    networks:
#      - movasat_network
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#    networks:
#      - movasat_network

volumes:
  movasat_postgresql:
    external: true
  movasat_static_volume:
    external: true
  movasat_files_volume:
    external: true
  movasat_mongo:
    external: true
  mongo:
    external: true
networks:
  movasat_network:
    external: true
  nginx_network:
    external: true
  default: